name: Hello World Action

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"
