name: Hello World Action

on:
  push:
    branches:
      - main

jobs:
  try-self-hosted:
    runs-on: self-hosted
    continue-on-error: true # Allows the workflow to continue if this job fails
    steps:
      - name: Print message
        run: echo "Running on self-hosted runner"

  fallback:
    needs: try-self-hosted
    if: failure() # Only runs if the self-hosted job fails
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Fallback to GitHub-hosted runner"
